<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Date &amp; Time Data with lubridate | Introduction to R for health data analysis</title>
  <meta name="description" content="Intro to R." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Date &amp; Time Data with lubridate | Introduction to R for health data analysis" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Intro to R." />
  <meta name="github-repo" content="ehsanx/intro2R" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Date &amp; Time Data with lubridate | Introduction to R for health data analysis" />
  
  <meta name="twitter:description" content="Intro to R." />
  

<meta name="author" content="Ehsan Karim, An Hoang and Yang Qu" />


<meta name="date" content="2021-09-05" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="data-visualization-with-ggplot2.html"/>
<link rel="next" href="data-summary-with-tableone.html"/>
<script src="libs/header-attrs-2.9/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script type="text/javascript">

// toggle visibility of R source blocks in R Markdown output
function toggle_R() {
  var x = document.getElementsByClassName('r');
  if (x.length == 0) return;
  function toggle_vis(o) {
    var d = o.style.display;
    o.style.display = (d == 'block' || d == '') ? 'none':'block';
  }

  for (i = 0; i < x.length; i++) {
    var y = x[i];
    if (y.tagName.toLowerCase() === 'pre') toggle_vis(y);
  }

    var elem = document.getElementById("myButton1");
    if (elem.value === "Hide Global") elem.value = "Show Global";
    else elem.value = "Hide Global";
}

document.write('<input onclick="toggle_R();" type="button" value="Hide Global" id="myButton1" style="position: absolute; top: 10%; right: 2%; z-index: 200"></input>')

</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Intro to R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#main-references"><i class="fa fa-check"></i>Main references</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#version-history"><i class="fa fa-check"></i>Version history</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#contributor-list"><i class="fa fa-check"></i>Contributor list</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#license"><i class="fa fa-check"></i>License</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="r-and-rstudio-set-up.html"><a href="r-and-rstudio-set-up.html"><i class="fa fa-check"></i><b>1</b> R and RStudio set up</a>
<ul>
<li class="chapter" data-level="1.1" data-path="r-and-rstudio-set-up.html"><a href="r-and-rstudio-set-up.html#instructions"><i class="fa fa-check"></i><b>1.1</b> Instructions</a></li>
<li class="chapter" data-level="1.2" data-path="r-and-rstudio-set-up.html"><a href="r-and-rstudio-set-up.html#learning-objectives"><i class="fa fa-check"></i><b>1.2</b> Learning Objectives</a></li>
<li class="chapter" data-level="1.3" data-path="r-and-rstudio-set-up.html"><a href="r-and-rstudio-set-up.html#what-is-r"><i class="fa fa-check"></i><b>1.3</b> What is R?</a></li>
<li class="chapter" data-level="1.4" data-path="r-and-rstudio-set-up.html"><a href="r-and-rstudio-set-up.html#what-is-rstudio"><i class="fa fa-check"></i><b>1.4</b> What is RStudio?</a></li>
<li class="chapter" data-level="1.5" data-path="r-and-rstudio-set-up.html"><a href="r-and-rstudio-set-up.html#download-and-install-r"><i class="fa fa-check"></i><b>1.5</b> Download and Install R</a></li>
<li class="chapter" data-level="1.6" data-path="r-and-rstudio-set-up.html"><a href="r-and-rstudio-set-up.html#download-and-install-rstudio"><i class="fa fa-check"></i><b>1.6</b> Download and Install RStudio</a></li>
<li class="chapter" data-level="1.7" data-path="r-and-rstudio-set-up.html"><a href="r-and-rstudio-set-up.html#rstudio-basics"><i class="fa fa-check"></i><b>1.7</b> RStudio Basics</a></li>
<li class="chapter" data-level="1.8" data-path="r-and-rstudio-set-up.html"><a href="r-and-rstudio-set-up.html#summary-and-takeaways"><i class="fa fa-check"></i><b>1.8</b> Summary and Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>2</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#instructions-1"><i class="fa fa-check"></i><b>2.1</b> Instructions</a></li>
<li class="chapter" data-level="2.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#learning-objectives-1"><i class="fa fa-check"></i><b>2.2</b> Learning Objectives</a></li>
<li class="chapter" data-level="2.3" data-path="introduction-to-r.html"><a href="introduction-to-r.html#set-up-basics"><i class="fa fa-check"></i><b>2.3</b> Set Up Basics</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#working-directory"><i class="fa fa-check"></i><b>2.3.1</b> Working Directory</a></li>
<li class="chapter" data-level="2.3.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#installing-and-attaching-packages"><i class="fa fa-check"></i><b>2.3.2</b> Installing and Attaching Packages</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="introduction-to-r.html"><a href="introduction-to-r.html#arithmetic-operators"><i class="fa fa-check"></i><b>2.4</b> Arithmetic Operators</a>
<ul>
<li><a href="introduction-to-r.html#try-it-yourself-2.12.1"><span>Try it yourself 2.1</span></a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="introduction-to-r.html"><a href="introduction-to-r.html#logical-operators"><i class="fa fa-check"></i><b>2.5</b> Logical Operators</a>
<ul>
<li><a href="introduction-to-r.html#try-it-yourself-2.22.2"><span>Try it yourself 2.2</span></a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="introduction-to-r.html"><a href="introduction-to-r.html#most-common-data-types-in-r"><i class="fa fa-check"></i><b>2.6</b> Most Common Data Types In R</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#strings"><i class="fa fa-check"></i><b>2.6.1</b> Strings</a></li>
<li class="chapter" data-level="2.6.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#vectors"><i class="fa fa-check"></i><b>2.6.2</b> Vectors</a></li>
<li><a href="introduction-to-r.html#try-it-yourself-2.32.3"><span>Try it yourself 2.3</span></a></li>
<li><a href="introduction-to-r.html#try-it-yourself-2.42.4"><span>Try it yourself 2.4</span></a></li>
<li class="chapter" data-level="2.6.3" data-path="introduction-to-r.html"><a href="introduction-to-r.html#lists"><i class="fa fa-check"></i><b>2.6.3</b> Lists</a></li>
<li class="chapter" data-level="2.6.4" data-path="introduction-to-r.html"><a href="introduction-to-r.html#dataframe"><i class="fa fa-check"></i><b>2.6.4</b> Dataframe</a></li>
<li><a href="introduction-to-r.html#try-it-yourself-2.52.5"><span>Try it yourself 2.5</span></a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="introduction-to-r.html"><a href="introduction-to-r.html#exploring-a-dataset"><i class="fa fa-check"></i><b>2.7</b> Exploring a Dataset</a>
<ul>
<li><a href="introduction-to-r.html#try-it-yourself-2.62.6"><span>Try it yourself 2.6</span></a></li>
<li class="chapter" data-level="2.7.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#dimensions"><i class="fa fa-check"></i><b>2.7.1</b> Dimensions</a></li>
<li class="chapter" data-level="2.7.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#structure"><i class="fa fa-check"></i><b>2.7.2</b> Structure</a></li>
<li class="chapter" data-level="2.7.3" data-path="introduction-to-r.html"><a href="introduction-to-r.html#class"><i class="fa fa-check"></i><b>2.7.3</b> Class</a></li>
<li><a href="introduction-to-r.html#try-it-yourself-2.72.7"><span>Try it yourself 2.7</span></a></li>
<li class="chapter" data-level="2.7.4" data-path="introduction-to-r.html"><a href="introduction-to-r.html#length"><i class="fa fa-check"></i><b>2.7.4</b> Length</a></li>
<li><a href="introduction-to-r.html#try-it-yourself-2.82.8"><span>Try it yourself 2.8</span></a></li>
<li class="chapter" data-level="2.7.5" data-path="introduction-to-r.html"><a href="introduction-to-r.html#head-and-tail"><i class="fa fa-check"></i><b>2.7.5</b> Head and Tail</a></li>
<li class="chapter" data-level="2.7.6" data-path="introduction-to-r.html"><a href="introduction-to-r.html#mathematical-functions-in-r"><i class="fa fa-check"></i><b>2.7.6</b> Mathematical Functions in R</a></li>
<li><a href="introduction-to-r.html#try-it-yourself-2.92.9"><span>Try it yourself 2.9</span></a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="introduction-to-r.html"><a href="introduction-to-r.html#writing-a-new-function-in-r"><i class="fa fa-check"></i><b>2.8</b> Writing a New Function In R</a></li>
<li class="chapter" data-level="2.9" data-path="introduction-to-r.html"><a href="introduction-to-r.html#for-loops"><i class="fa fa-check"></i><b>2.9</b> For Loops</a></li>
<li class="chapter" data-level="2.10" data-path="introduction-to-r.html"><a href="introduction-to-r.html#help-within-and-outside-of-r"><i class="fa fa-check"></i><b>2.10</b> Help Within and Outside Of R</a>
<ul>
<li class="chapter" data-level="2.10.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#within-r"><i class="fa fa-check"></i><b>2.10.1</b> Within R</a></li>
<li class="chapter" data-level="2.10.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#outside-of-r"><i class="fa fa-check"></i><b>2.10.2</b> Outside of R</a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="introduction-to-r.html"><a href="introduction-to-r.html#summary-and-takeaways-1"><i class="fa fa-check"></i><b>2.11</b> Summary and Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="importing-data-into-r-with-readr.html"><a href="importing-data-into-r-with-readr.html"><i class="fa fa-check"></i><b>3</b> Importing Data into R with readr</a>
<ul>
<li class="chapter" data-level="3.1" data-path="importing-data-into-r-with-readr.html"><a href="importing-data-into-r-with-readr.html#instructions-2"><i class="fa fa-check"></i><b>3.1</b> Instructions</a></li>
<li class="chapter" data-level="3.2" data-path="importing-data-into-r-with-readr.html"><a href="importing-data-into-r-with-readr.html#learning-objectives-2"><i class="fa fa-check"></i><b>3.2</b> Learning Objectives</a></li>
<li class="chapter" data-level="3.3" data-path="importing-data-into-r-with-readr.html"><a href="importing-data-into-r-with-readr.html#set-up"><i class="fa fa-check"></i><b>3.3</b> Set Up</a></li>
<li class="chapter" data-level="3.4" data-path="importing-data-into-r-with-readr.html"><a href="importing-data-into-r-with-readr.html#basics-of-importing-a-csv-file-into-r"><i class="fa fa-check"></i><b>3.4</b> Basics Of Importing a CSV File Into R</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="importing-data-into-r-with-readr.html"><a href="importing-data-into-r-with-readr.html#method-1-setting-a-different-working-directory"><i class="fa fa-check"></i><b>3.4.1</b> Method 1: Setting a Different Working Directory</a></li>
<li class="chapter" data-level="3.4.2" data-path="importing-data-into-r-with-readr.html"><a href="importing-data-into-r-with-readr.html#method-2-copying-the-exact-pathway-of-the-file"><i class="fa fa-check"></i><b>3.4.2</b> Method 2: Copying the Exact Pathway of the File</a></li>
<li><a href="importing-data-into-r-with-readr.html#try-it-yourself-3.13.1"><span>Try it yourself 3.1</span></a></li>
<li class="chapter" data-level="3.4.3" data-path="importing-data-into-r-with-readr.html"><a href="importing-data-into-r-with-readr.html#key-notes-about-importing-data-into-r"><i class="fa fa-check"></i><b>3.4.3</b> Key Notes About Importing Data into R</a></li>
<li><a href="importing-data-into-r-with-readr.html#try-it-yourself-3.23.2"><span>Try it yourself 3.2</span></a></li>
<li class="chapter" data-level="3.4.4" data-path="importing-data-into-r-with-readr.html"><a href="importing-data-into-r-with-readr.html#column-specification"><i class="fa fa-check"></i><b>3.4.4</b> Column Specification</a></li>
<li><a href="importing-data-into-r-with-readr.html#try-it-yourself-3.33.3"><span>Try it yourself 3.3</span></a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="importing-data-into-r-with-readr.html"><a href="importing-data-into-r-with-readr.html#more-arguments-of-read_csv"><i class="fa fa-check"></i><b>3.5</b> More Arguments Of read_csv</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="importing-data-into-r-with-readr.html"><a href="importing-data-into-r-with-readr.html#skip"><i class="fa fa-check"></i><b>3.5.1</b> Skip</a></li>
<li><a href="importing-data-into-r-with-readr.html#try-it-yourself-3.43.4"><span>Try it yourself 3.4</span></a></li>
<li class="chapter" data-level="3.5.2" data-path="importing-data-into-r-with-readr.html"><a href="importing-data-into-r-with-readr.html#remove-header-header-names"><i class="fa fa-check"></i><b>3.5.2</b> Remove Header &amp; Header Names</a></li>
<li class="chapter" data-level="3.5.3" data-path="importing-data-into-r-with-readr.html"><a href="importing-data-into-r-with-readr.html#missing-values"><i class="fa fa-check"></i><b>3.5.3</b> Missing Values</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="importing-data-into-r-with-readr.html"><a href="importing-data-into-r-with-readr.html#importing-other-file-types-into-r"><i class="fa fa-check"></i><b>3.6</b> Importing Other File Types into R</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="importing-data-into-r-with-readr.html"><a href="importing-data-into-r-with-readr.html#text-file-txt"><i class="fa fa-check"></i><b>3.6.1</b> Text file (txt)</a></li>
<li class="chapter" data-level="3.6.2" data-path="importing-data-into-r-with-readr.html"><a href="importing-data-into-r-with-readr.html#excel-file-xlsx"><i class="fa fa-check"></i><b>3.6.2</b> Excel file (xlsx)</a></li>
<li><a href="importing-data-into-r-with-readr.html#try-it-yourself-3.53.5"><span>Try it yourself 3.5</span></a></li>
<li class="chapter" data-level="3.6.3" data-path="importing-data-into-r-with-readr.html"><a href="importing-data-into-r-with-readr.html#xpt-file-extension"><i class="fa fa-check"></i><b>3.6.3</b> XPT File Extension</a></li>
<li class="chapter" data-level="3.6.4" data-path="importing-data-into-r-with-readr.html"><a href="importing-data-into-r-with-readr.html#statistical-analysis-software-sas"><i class="fa fa-check"></i><b>3.6.4</b> Statistical Analysis Software (SAS)</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="importing-data-into-r-with-readr.html"><a href="importing-data-into-r-with-readr.html#exporting-the-data-frame-from-r"><i class="fa fa-check"></i><b>3.7</b> Exporting the Data Frame From R</a></li>
<li class="chapter" data-level="3.8" data-path="importing-data-into-r-with-readr.html"><a href="importing-data-into-r-with-readr.html#summary-and-takeaways-2"><i class="fa fa-check"></i><b>3.8</b> Summary and Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="introduction-to-nhanes.html"><a href="introduction-to-nhanes.html"><i class="fa fa-check"></i><b>4</b> Introduction to NHANES</a>
<ul>
<li class="chapter" data-level="4.1" data-path="introduction-to-nhanes.html"><a href="introduction-to-nhanes.html#instructions-3"><i class="fa fa-check"></i><b>4.1</b> Instructions</a></li>
<li class="chapter" data-level="4.2" data-path="introduction-to-nhanes.html"><a href="introduction-to-nhanes.html#learning-objectives-3"><i class="fa fa-check"></i><b>4.2</b> Learning Objectives</a></li>
<li class="chapter" data-level="4.3" data-path="introduction-to-nhanes.html"><a href="introduction-to-nhanes.html#introduction-to-nhanes-1"><i class="fa fa-check"></i><b>4.3</b> Introduction to NHANES</a></li>
<li class="chapter" data-level="4.4" data-path="introduction-to-nhanes.html"><a href="introduction-to-nhanes.html#importing-nhanes-dataset-from-website"><i class="fa fa-check"></i><b>4.4</b> Importing NHANES dataset from website</a></li>
<li class="chapter" data-level="4.5" data-path="introduction-to-nhanes.html"><a href="introduction-to-nhanes.html#importing-nhanes-dataset-from-r-package-nhanesa"><i class="fa fa-check"></i><b>4.5</b> Importing NHANES dataset from R package: nhanesA</a>
<ul>
<li><a href="introduction-to-nhanes.html#try-it-yourself-4.14.1">Try it yourself 4.1]<span>4.1</span></a></li>
<li class="chapter" data-level="4.5.1" data-path="introduction-to-nhanes.html"><a href="introduction-to-nhanes.html#other-packages-in-r"><i class="fa fa-check"></i><b>4.5.1</b> Other packages in R</a></li>
<li class="chapter" data-level="4.5.2" data-path="introduction-to-nhanes.html"><a href="introduction-to-nhanes.html#alternative-ways-to-download-nhanes"><i class="fa fa-check"></i><b>4.5.2</b> Alternative ways to download NHANES</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="introduction-to-nhanes.html"><a href="introduction-to-nhanes.html#summary-and-takeaways-3"><i class="fa fa-check"></i><b>4.6</b> Summary and Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-analysis-with-dplyr.html"><a href="data-analysis-with-dplyr.html"><i class="fa fa-check"></i><b>5</b> Data Analysis with dplyr</a>
<ul>
<li class="chapter" data-level="5.1" data-path="data-analysis-with-dplyr.html"><a href="data-analysis-with-dplyr.html#instructions-4"><i class="fa fa-check"></i><b>5.1</b> Instructions</a></li>
<li class="chapter" data-level="5.2" data-path="data-analysis-with-dplyr.html"><a href="data-analysis-with-dplyr.html#learning-objectives-4"><i class="fa fa-check"></i><b>5.2</b> Learning Objectives</a></li>
<li class="chapter" data-level="5.3" data-path="data-analysis-with-dplyr.html"><a href="data-analysis-with-dplyr.html#set-up-1"><i class="fa fa-check"></i><b>5.3</b> Set up</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="data-analysis-with-dplyr.html"><a href="data-analysis-with-dplyr.html#install-and-load-packages"><i class="fa fa-check"></i><b>5.3.1</b> Install and load packages</a></li>
<li class="chapter" data-level="5.3.2" data-path="data-analysis-with-dplyr.html"><a href="data-analysis-with-dplyr.html#set-working-directory"><i class="fa fa-check"></i><b>5.3.2</b> Set working directory</a></li>
<li class="chapter" data-level="5.3.3" data-path="data-analysis-with-dplyr.html"><a href="data-analysis-with-dplyr.html#import-dataset"><i class="fa fa-check"></i><b>5.3.3</b> Import dataset</a></li>
<li class="chapter" data-level="5.3.4" data-path="data-analysis-with-dplyr.html"><a href="data-analysis-with-dplyr.html#explore-our-dataset"><i class="fa fa-check"></i><b>5.3.4</b> Explore our dataset</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="data-analysis-with-dplyr.html"><a href="data-analysis-with-dplyr.html#dataset-preparation"><i class="fa fa-check"></i><b>5.4</b> Dataset Preparation</a>
<ul>
<li><a href="data-analysis-with-dplyr.html#try-it-yourself-5.15.1"><span>Try it yourself 5.1</span></a></li>
<li><a href="data-analysis-with-dplyr.html#try-it-yourself-5.25.2"><span>Try it yourself 5.2</span></a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="data-analysis-with-dplyr.html"><a href="data-analysis-with-dplyr.html#filter"><i class="fa fa-check"></i><b>5.5</b> Filter</a>
<ul>
<li><a href="data-analysis-with-dplyr.html#try-it-yourself-5.35.3"><span>Try it yourself 5.3</span></a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="data-analysis-with-dplyr.html"><a href="data-analysis-with-dplyr.html#re-order-the-rows"><i class="fa fa-check"></i><b>5.6</b> Re-order the Rows</a>
<ul>
<li><a href="data-analysis-with-dplyr.html#try-it-yourself-5.45.4"><span>Try it yourself 5.4</span></a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="data-analysis-with-dplyr.html"><a href="data-analysis-with-dplyr.html#add-new-variables"><i class="fa fa-check"></i><b>5.7</b> Add new variables</a>
<ul>
<li><a href="data-analysis-with-dplyr.html#try-it-yourself-5.55.5"><span>Try it yourself 5.5</span></a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="data-analysis-with-dplyr.html"><a href="data-analysis-with-dplyr.html#summary-statistics-and-group_by"><i class="fa fa-check"></i><b>5.8</b> Summary Statistics and group_by</a>
<ul>
<li><a href="data-analysis-with-dplyr.html#try-it-yourself-5.65.6"><span>Try it yourself 5.6</span></a></li>
<li class="chapter" data-level="5.8.1" data-path="data-analysis-with-dplyr.html"><a href="data-analysis-with-dplyr.html#group_by-extension"><i class="fa fa-check"></i><b>5.8.1</b> Group_by() extension</a></li>
<li><a href="data-analysis-with-dplyr.html#try-it-yourself-5.75.7"><span>Try it yourself 5.7</span></a></li>
<li><a href="data-analysis-with-dplyr.html#try-it-yourself-5.85.8"><span>Try it yourself 5.8</span></a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="data-analysis-with-dplyr.html"><a href="data-analysis-with-dplyr.html#pipe"><i class="fa fa-check"></i><b>5.9</b> Pipe</a>
<ul>
<li><a href="data-analysis-with-dplyr.html#try-it-yourself-5.95.9"><span>Try it yourself 5.9</span></a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="data-analysis-with-dplyr.html"><a href="data-analysis-with-dplyr.html#summary-of-dealing-with-missing-values"><i class="fa fa-check"></i><b>5.10</b> Summary of dealing with missing values</a></li>
<li class="chapter" data-level="5.11" data-path="data-analysis-with-dplyr.html"><a href="data-analysis-with-dplyr.html#alternatives-to-nhanestranslate"><i class="fa fa-check"></i><b>5.11</b> Alternatives to NHANESTranslate()</a>
<ul>
<li class="chapter" data-level="5.11.1" data-path="data-analysis-with-dplyr.html"><a href="data-analysis-with-dplyr.html#case_when"><i class="fa fa-check"></i><b>5.11.1</b> <code>case_when()</code></a></li>
</ul></li>
<li class="chapter" data-level="5.12" data-path="data-analysis-with-dplyr.html"><a href="data-analysis-with-dplyr.html#translating-nhanes-using-case_when"><i class="fa fa-check"></i><b>5.12</b> Translating NHANES using <code>case_when()</code></a></li>
<li class="chapter" data-level="5.13" data-path="data-analysis-with-dplyr.html"><a href="data-analysis-with-dplyr.html#recode-from-dplyr"><i class="fa fa-check"></i><b>5.13</b> <code>recode()</code> from dplyr</a></li>
<li class="chapter" data-level="5.14" data-path="data-analysis-with-dplyr.html"><a href="data-analysis-with-dplyr.html#recode-from-car"><i class="fa fa-check"></i><b>5.14</b> <code>recode()</code> from car</a></li>
<li class="chapter" data-level="5.15" data-path="data-analysis-with-dplyr.html"><a href="data-analysis-with-dplyr.html#summary-and-takeaways-4"><i class="fa fa-check"></i><b>5.15</b> Summary and Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html"><i class="fa fa-check"></i><b>6</b> Data Visualization with ggplot2</a>
<ul>
<li class="chapter" data-level="6.1" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#instructions-5"><i class="fa fa-check"></i><b>6.1</b> Instructions</a></li>
<li class="chapter" data-level="6.2" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#learning-objectives-5"><i class="fa fa-check"></i><b>6.2</b> Learning Objectives</a></li>
<li class="chapter" data-level="6.3" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#set-up-2"><i class="fa fa-check"></i><b>6.3</b> Set Up</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#loading-required-packages"><i class="fa fa-check"></i><b>6.3.1</b> Loading required packages</a></li>
<li class="chapter" data-level="6.3.2" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#importing-data"><i class="fa fa-check"></i><b>6.3.2</b> Importing Data</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#ggplot-and-point-geometrics"><i class="fa fa-check"></i><b>6.4</b> ggplot() and Point Geometrics</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#point-geometrics"><i class="fa fa-check"></i><b>6.4.1</b> Point Geometrics</a></li>
<li><a href="data-visualization-with-ggplot2.html#try-it-yourself-6.16.1"><span>Try it yourself 6.1</span></a></li>
<li class="chapter" data-level="6.4.2" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#aesthetics"><i class="fa fa-check"></i><b>6.4.2</b> Aesthetics</a></li>
<li><a href="data-visualization-with-ggplot2.html#try-it-yourself-6.26.2"><span>Try it yourself 6.2</span></a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#multiple-geometric-functions-under-one-ggplot"><i class="fa fa-check"></i><b>6.5</b> Multiple Geometric Functions under one ggplot</a></li>
<li class="chapter" data-level="6.6" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#other-geometric-functions"><i class="fa fa-check"></i><b>6.6</b> Other Geometric Functions</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#bar-graph"><i class="fa fa-check"></i><b>6.6.1</b> Bar graph</a></li>
<li class="chapter" data-level="6.6.2" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#line-graph"><i class="fa fa-check"></i><b>6.6.2</b> Line Graph</a></li>
<li class="chapter" data-level="6.6.3" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#boxplot"><i class="fa fa-check"></i><b>6.6.3</b> Boxplot</a></li>
<li class="chapter" data-level="6.6.4" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#frequency-polygon"><i class="fa fa-check"></i><b>6.6.4</b> Frequency Polygon</a></li>
<li><a href="data-visualization-with-ggplot2.html#try-it-yourself-6.36.3"><span>Try it yourself 6.3</span></a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#facet-functions"><i class="fa fa-check"></i><b>6.7</b> Facet Functions</a>
<ul>
<li><a href="data-visualization-with-ggplot2.html#try-it-yourself-6.46.4"><span>Try it yourself 6.4</span></a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#customizing-graph-elements"><i class="fa fa-check"></i><b>6.8</b> Customizing Graph Elements</a>
<ul>
<li class="chapter" data-level="" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#try-it-yourself-6.5"><i class="fa fa-check"></i>Try it yourself 6.5</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#saving-our-graphs"><i class="fa fa-check"></i><b>6.9</b> Saving Our Graphs</a></li>
<li class="chapter" data-level="6.10" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#summary-and-takeaways-5"><i class="fa fa-check"></i><b>6.10</b> Summary and Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="date-time-data-with-lubridate.html"><a href="date-time-data-with-lubridate.html"><i class="fa fa-check"></i><b>7</b> Date &amp; Time Data with lubridate</a>
<ul>
<li class="chapter" data-level="7.1" data-path="date-time-data-with-lubridate.html"><a href="date-time-data-with-lubridate.html#instructions-6"><i class="fa fa-check"></i><b>7.1</b> Instructions</a></li>
<li class="chapter" data-level="7.2" data-path="date-time-data-with-lubridate.html"><a href="date-time-data-with-lubridate.html#learning-objectives-6"><i class="fa fa-check"></i><b>7.2</b> Learning Objectives</a></li>
<li class="chapter" data-level="7.3" data-path="date-time-data-with-lubridate.html"><a href="date-time-data-with-lubridate.html#set-up-3"><i class="fa fa-check"></i><b>7.3</b> Set Up</a></li>
<li class="chapter" data-level="7.4" data-path="date-time-data-with-lubridate.html"><a href="date-time-data-with-lubridate.html#exploring-friends-visits-dataset"><i class="fa fa-check"></i><b>7.4</b> Exploring Friends Visits Dataset</a></li>
<li class="chapter" data-level="7.5" data-path="date-time-data-with-lubridate.html"><a href="date-time-data-with-lubridate.html#creating-datetime-data"><i class="fa fa-check"></i><b>7.5</b> Creating Date/Time Data</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="date-time-data-with-lubridate.html"><a href="date-time-data-with-lubridate.html#strings-1"><i class="fa fa-check"></i><b>7.5.1</b> Strings</a></li>
<li><a href="date-time-data-with-lubridate.html#try-it-yourself-7.17.1"><span>Try it yourself 7.1</span></a></li>
<li class="chapter" data-level="7.5.2" data-path="date-time-data-with-lubridate.html"><a href="date-time-data-with-lubridate.html#existing-datetime-data"><i class="fa fa-check"></i><b>7.5.2</b> Existing Date/Time Data</a></li>
<li class="chapter" data-level="7.5.3" data-path="date-time-data-with-lubridate.html"><a href="date-time-data-with-lubridate.html#dataset"><i class="fa fa-check"></i><b>7.5.3</b> Dataset</a></li>
<li class="chapter" data-level="" data-path="date-time-data-with-lubridate.html"><a href="date-time-data-with-lubridate.html#functions-debunked-20"><i class="fa fa-check"></i>Functions Debunked</a></li>
<li><a href="date-time-data-with-lubridate.html#try-it-yourself-7.27.2"><span>Try it yourself 7.2</span></a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="date-time-data-with-lubridate.html"><a href="date-time-data-with-lubridate.html#retrieving-information-from-datetime-data"><i class="fa fa-check"></i><b>7.6</b> Retrieving Information from Date/Time Data</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="date-time-data-with-lubridate.html"><a href="date-time-data-with-lubridate.html#year"><i class="fa fa-check"></i><b>7.6.1</b> Year</a></li>
<li class="chapter" data-level="7.6.2" data-path="date-time-data-with-lubridate.html"><a href="date-time-data-with-lubridate.html#month"><i class="fa fa-check"></i><b>7.6.2</b> Month</a></li>
<li class="chapter" data-level="7.6.3" data-path="date-time-data-with-lubridate.html"><a href="date-time-data-with-lubridate.html#week"><i class="fa fa-check"></i><b>7.6.3</b> Week</a></li>
<li><a href="date-time-data-with-lubridate.html#try-it-yourself-7.37.3"><span>Try it yourself 7.3</span></a></li>
<li class="chapter" data-level="7.6.4" data-path="date-time-data-with-lubridate.html"><a href="date-time-data-with-lubridate.html#plotting-retrieved-information"><i class="fa fa-check"></i><b>7.6.4</b> Plotting Retrieved Information</a></li>
<li><a href="date-time-data-with-lubridate.html#try-it-yourself-7.47.4"><span>Try it yourself 7.4</span></a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="date-time-data-with-lubridate.html"><a href="date-time-data-with-lubridate.html#updating-plotting-datetime-data"><i class="fa fa-check"></i><b>7.7</b> Updating &amp; Plotting Date/Time Data</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="date-time-data-with-lubridate.html"><a href="date-time-data-with-lubridate.html#update"><i class="fa fa-check"></i><b>7.7.1</b> Update</a></li>
<li><a href="date-time-data-with-lubridate.html#try-it-yourself-7.57.5"><span>Try it yourself 7.5</span></a></li>
<li class="chapter" data-level="7.7.2" data-path="date-time-data-with-lubridate.html"><a href="date-time-data-with-lubridate.html#plotting-datetime"><i class="fa fa-check"></i><b>7.7.2</b> Plotting Date/Time</a></li>
<li><a href="date-time-data-with-lubridate.html#try-it-yourself-7.67.6"><span>Try it yourself 7.6</span></a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="date-time-data-with-lubridate.html"><a href="date-time-data-with-lubridate.html#arithmetic-operators-with-datetime"><i class="fa fa-check"></i><b>7.8</b> Arithmetic Operators with Date/Time</a>
<ul>
<li class="chapter" data-level="7.8.1" data-path="date-time-data-with-lubridate.html"><a href="date-time-data-with-lubridate.html#basic-arithmetic"><i class="fa fa-check"></i><b>7.8.1</b> Basic Arithmetic</a></li>
<li class="chapter" data-level="7.8.2" data-path="date-time-data-with-lubridate.html"><a href="date-time-data-with-lubridate.html#account-for-leap-years-and-daylight-savings"><i class="fa fa-check"></i><b>7.8.2</b> Account for Leap Years and Daylight Savings</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="date-time-data-with-lubridate.html"><a href="date-time-data-with-lubridate.html#summary-and-takeaways-6"><i class="fa fa-check"></i><b>7.9</b> Summary and Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="data-summary-with-tableone.html"><a href="data-summary-with-tableone.html"><i class="fa fa-check"></i><b>8</b> Data Summary with tableone</a>
<ul>
<li class="chapter" data-level="8.1" data-path="data-summary-with-tableone.html"><a href="data-summary-with-tableone.html#instructions-7"><i class="fa fa-check"></i><b>8.1</b> Instructions</a></li>
<li class="chapter" data-level="8.2" data-path="data-summary-with-tableone.html"><a href="data-summary-with-tableone.html#learning-objectives-7"><i class="fa fa-check"></i><b>8.2</b> Learning Objectives</a></li>
<li class="chapter" data-level="8.3" data-path="data-summary-with-tableone.html"><a href="data-summary-with-tableone.html#set-up-4"><i class="fa fa-check"></i><b>8.3</b> Set Up</a></li>
<li class="chapter" data-level="8.4" data-path="data-summary-with-tableone.html"><a href="data-summary-with-tableone.html#what-is-tableone"><i class="fa fa-check"></i><b>8.4</b> What is tableone?</a></li>
<li class="chapter" data-level="8.5" data-path="data-summary-with-tableone.html"><a href="data-summary-with-tableone.html#creating-a-tableone"><i class="fa fa-check"></i><b>8.5</b> Creating a tableone</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="data-summary-with-tableone.html"><a href="data-summary-with-tableone.html#createtableone"><i class="fa fa-check"></i><b>8.5.1</b> CreateTableOne</a></li>
<li class="chapter" data-level="8.5.2" data-path="data-summary-with-tableone.html"><a href="data-summary-with-tableone.html#solution-1-nhanestranslate-createtableone"><i class="fa fa-check"></i><b>8.5.2</b> Solution 1: nhanesTranslate &amp; CreateTableOne</a></li>
<li><a href="data-summary-with-tableone.html#try-it-yourself-8.18.1"><span>Try it yourself 8.1</span></a></li>
<li class="chapter" data-level="8.5.3" data-path="data-summary-with-tableone.html"><a href="data-summary-with-tableone.html#solution-2-identify-numerical-categorical-data"><i class="fa fa-check"></i><b>8.5.3</b> Solution 2: Identify Numerical Categorical Data</a></li>
<li><a href="data-summary-with-tableone.html#try-it-yourself-8.28.2"><span>Try it yourself 8.2</span></a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="data-summary-with-tableone.html"><a href="data-summary-with-tableone.html#other-arguments-to-customize-tableone"><i class="fa fa-check"></i><b>8.6</b> Other Arguments to Customize tableone</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="data-summary-with-tableone.html"><a href="data-summary-with-tableone.html#show-all-levels"><i class="fa fa-check"></i><b>8.6.1</b> Show All Levels</a></li>
<li class="chapter" data-level="8.6.2" data-path="data-summary-with-tableone.html"><a href="data-summary-with-tableone.html#nonnormal"><i class="fa fa-check"></i><b>8.6.2</b> Nonnormal</a></li>
<li><a href="data-summary-with-tableone.html#try-it-yourself-8.38.3"><span>Try it yourself 8.3</span></a></li>
<li class="chapter" data-level="8.6.3" data-path="data-summary-with-tableone.html"><a href="data-summary-with-tableone.html#show-categorical-or-continuous-variables-only"><i class="fa fa-check"></i><b>8.6.3</b> Show Categorical or Continuous Variables Only</a></li>
<li class="chapter" data-level="8.6.4" data-path="data-summary-with-tableone.html"><a href="data-summary-with-tableone.html#strata"><i class="fa fa-check"></i><b>8.6.4</b> Strata</a></li>
<li><a href="data-summary-with-tableone.html#try-it-yourself-8.48.4"><span>Try it yourself 8.4</span></a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="data-summary-with-tableone.html"><a href="data-summary-with-tableone.html#export-tableone"><i class="fa fa-check"></i><b>8.7</b> Export tableone</a></li>
<li class="chapter" data-level="8.8" data-path="data-summary-with-tableone.html"><a href="data-summary-with-tableone.html#alternatives-to-tableone"><i class="fa fa-check"></i><b>8.8</b> Alternatives to tableone</a>
<ul>
<li class="chapter" data-level="8.8.1" data-path="data-summary-with-tableone.html"><a href="data-summary-with-tableone.html#base-r"><i class="fa fa-check"></i><b>8.8.1</b> base R</a></li>
<li class="chapter" data-level="8.8.2" data-path="data-summary-with-tableone.html"><a href="data-summary-with-tableone.html#hmisc"><i class="fa fa-check"></i><b>8.8.2</b> Hmisc</a></li>
<li class="chapter" data-level="8.8.3" data-path="data-summary-with-tableone.html"><a href="data-summary-with-tableone.html#psych"><i class="fa fa-check"></i><b>8.8.3</b> psych</a></li>
<li class="chapter" data-level="8.8.4" data-path="data-summary-with-tableone.html"><a href="data-summary-with-tableone.html#desctable"><i class="fa fa-check"></i><b>8.8.4</b> desctable</a></li>
<li class="chapter" data-level="8.8.5" data-path="data-summary-with-tableone.html"><a href="data-summary-with-tableone.html#skimr"><i class="fa fa-check"></i><b>8.8.5</b> skimr</a></li>
</ul></li>
<li class="chapter" data-level="8.9" data-path="data-summary-with-tableone.html"><a href="data-summary-with-tableone.html#summary-and-takeaways-7"><i class="fa fa-check"></i><b>8.9</b> Summary and Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html"><i class="fa fa-check"></i><b>9</b> Appendix: Exercise Solutions</a>
<ul>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#tutorial-2-introduction-to-r"><i class="fa fa-check"></i>Tutorial 2: Introduction to R</a>
<ul>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section"><i class="fa fa-check"></i>2.1</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-1"><i class="fa fa-check"></i>2.2</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-2"><i class="fa fa-check"></i>2.3</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-3"><i class="fa fa-check"></i>2.4</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-4"><i class="fa fa-check"></i>2.5</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-5"><i class="fa fa-check"></i>2.6</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-6"><i class="fa fa-check"></i>2.7</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-7"><i class="fa fa-check"></i>2.8</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-8"><i class="fa fa-check"></i>2.9</a></li>
</ul></li>
<li class="chapter" data-level="9.1" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#tutorial-3-importing-data-into-r-with-readr"><i class="fa fa-check"></i><b>9.1</b> Tutorial 3: Importing Data into R with readr</a>
<ul>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-9"><i class="fa fa-check"></i>3.1</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-10"><i class="fa fa-check"></i>3.2</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-11"><i class="fa fa-check"></i>3.3</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-12"><i class="fa fa-check"></i>3.4</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-13"><i class="fa fa-check"></i>3.5</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#tutorial-4-introduction-to-nhanes"><i class="fa fa-check"></i><b>9.2</b> Tutorial 4: Introduction to NHANES</a>
<ul>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-14"><i class="fa fa-check"></i>4.1</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#tutorial-5-data-analysis-with-dplyr"><i class="fa fa-check"></i><b>9.3</b> Tutorial 5: Data Analysis with dplyr</a>
<ul>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-15"><i class="fa fa-check"></i>5.1</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-16"><i class="fa fa-check"></i>5.2</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-17"><i class="fa fa-check"></i>5.3</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-18"><i class="fa fa-check"></i>5.4</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-19"><i class="fa fa-check"></i>5.5</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-20"><i class="fa fa-check"></i>5.6</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-21"><i class="fa fa-check"></i>5.7</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-22"><i class="fa fa-check"></i>5.8</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-23"><i class="fa fa-check"></i>5.9</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#tutorial-6-data-visualization-with-ggplot2"><i class="fa fa-check"></i>Tutorial 6: Data Visualization with ggplot2</a>
<ul>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-24"><i class="fa fa-check"></i>6.1</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-25"><i class="fa fa-check"></i>6.2</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-26"><i class="fa fa-check"></i>6.3</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-27"><i class="fa fa-check"></i>6.4</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#tutorial-7-date-and-time-data-with-lubridate"><i class="fa fa-check"></i>Tutorial 7: Date and Time Data with lubridate</a>
<ul>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-28"><i class="fa fa-check"></i>7.1</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-29"><i class="fa fa-check"></i>7.2</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-30"><i class="fa fa-check"></i>7.3</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-31"><i class="fa fa-check"></i>7.4</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-32"><i class="fa fa-check"></i>7.5</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-33"><i class="fa fa-check"></i>7.6</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#tutorial-8-data-summary-with-tableone"><i class="fa fa-check"></i>Tutorial 8: Data Summary with tableone</a>
<ul>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-34"><i class="fa fa-check"></i>8.1</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-35"><i class="fa fa-check"></i>8.2</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-36"><i class="fa fa-check"></i>8.3</a></li>
<li class="chapter" data-level="" data-path="appendix-exercise-solutions.html"><a href="appendix-exercise-solutions.html#section-37"><i class="fa fa-check"></i>8.4</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://ehsank.com/" target="blank">Ehsan Karim</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to R for health data analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="date-time-data-with-lubridate" class="section level1" number="7">
<h1><span class="header-section-number">Chapter 7</span> Date &amp; Time Data with lubridate</h1>
<div id="instructions-6" class="section level2" number="7.1">
<h2><span class="header-section-number">7.1</span> Instructions</h2>
<p>In this tutorial, we will be exploring how to deal with date/time data in R using the lubridate package. This incudes creating new, retrieving information from existing, modifying, and conduct different arithmetic calculations on date/time data. We will also be plotting date/time data to visualize our dataset.</p>
<p>Accompanying this tutorial is <strong>a short <a href="https://forms.gle/zt9vGevq3zuqGBTG8">Google quiz</a></strong> for your own self-assessment. The instructions of this tutorial will clearly indicate when you should answer which question.</p>
</div>
<div id="learning-objectives-6" class="section level2" number="7.2">
<h2><span class="header-section-number">7.2</span> Learning Objectives</h2>
<ul>
<li>Understand the basics of the lubridate package and its simple datetime functions.</li>
<li>Know how to create date, time, and datetime data on R.</li>
<li>Know how to retrieve information from date/time data</li>
<li>Know how to modify date/time data</li>
<li>Know how to add, subtract, multiply, divide date/time data</li>
<li>Be familiar with graphs with date/time data.</li>
</ul>
</div>
<div id="set-up-3" class="section level2" number="7.3">
<h2><span class="header-section-number">7.3</span> Set Up</h2>
<p>For this tutorial, we will need the <strong>lubridate</strong> package with functions that will allow us to deal with date/time data. This package is also part of the tidyverse core that also houses readr, dplyr, and ggplot2.</p>
<div class="sourceCode" id="cb410"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb410-1"><a href="date-time-data-with-lubridate.html#cb410-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(lubridate)</span></span>
<span id="cb410-2"><a href="date-time-data-with-lubridate.html#cb410-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span></code></pre></div>
<p>We will also be using the <strong>Friend visits.csv</strong> dataset. This dataset was especially prepared for this tutorial, and it includes specific data that will help us understand lubridate more! In short, this made-up dataset contains information about the times that our host(s) had friends over and the times that they left.</p>
<p>Let’s import this dataset into R now using <code>read_csv()</code> from the package readr.</p>
<div class="sourceCode" id="cb411"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb411-1"><a href="date-time-data-with-lubridate.html#cb411-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&quot;readr&quot;)</span></span>
<span id="cb411-2"><a href="date-time-data-with-lubridate.html#cb411-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span></code></pre></div>
<div class="sourceCode" id="cb412"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb412-1"><a href="date-time-data-with-lubridate.html#cb412-1" aria-hidden="true" tabindex="-1"></a>visits <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/Friends visits.csv&quot;</span>)</span></code></pre></div>
<pre><code>## Rows: 365 Columns: 8</code></pre>
<pre><code>## -- Column specification --------------------------------------------------------
## Delimiter: &quot;,&quot;
## dbl (8): Friend, Year, Month, Day, Hour, Minute, Second, Left_time</code></pre>
<pre><code>## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb416"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb416-1"><a href="date-time-data-with-lubridate.html#cb416-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(visits)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 8
##   Friend  Year Month   Day  Hour Minute Second Left_time
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;
## 1      1  2015     1     1    19      4     22       830
## 2      2  2015     1     2     9     20     19       850
## 3      3  2015     1     3    22     23      9       923
## 4      4  2015     1     4     9     22     51      1004
## 5      5  2015     1     5    18      1     16       812
## 6      6  2015     1     6     5     59      2       740</code></pre>
<p>We will also need the <strong>dplyr</strong> and <strong>ggplot2</strong> packages to plot a few graphs.</p>
<div class="sourceCode" id="cb418"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb418-1"><a href="date-time-data-with-lubridate.html#cb418-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(dplyr)</span></span>
<span id="cb418-2"><a href="date-time-data-with-lubridate.html#cb418-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb418-3"><a href="date-time-data-with-lubridate.html#cb418-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb418-4"><a href="date-time-data-with-lubridate.html#cb418-4" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(ggplot2)</span></span>
<span id="cb418-5"><a href="date-time-data-with-lubridate.html#cb418-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div>
</div>
<div id="exploring-friends-visits-dataset" class="section level2" number="7.4">
<h2><span class="header-section-number">7.4</span> Exploring Friends Visits Dataset</h2>
<p>Before we jump into lubridate and date/time data, let’s first explore the Friends visits dataset that we will be using today.</p>
<div class="sourceCode" id="cb419"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb419-1"><a href="date-time-data-with-lubridate.html#cb419-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(visits, <span class="dv">20</span>)</span></code></pre></div>
<pre><code>## # A tibble: 20 x 8
##    Friend  Year Month   Day  Hour Minute Second Left_time
##     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;
##  1      1  2015     1     1    19      4     22       830
##  2      2  2015     1     2     9     20     19       850
##  3      3  2015     1     3    22     23      9       923
##  4      4  2015     1     4     9     22     51      1004
##  5      5  2015     1     5    18      1     16       812
##  6      6  2015     1     6     5     59      2       740
##  7      7  2015     1     7     9     45     55       913
##  8      8  2015     1     8    12      3     33       709
##  9      9  2015     1     9    17      9     59       838
## 10     10  2015     1    10    16     44     43       753
## 11     11  2015     1    11     0     31     28       849
## 12     12  2015     1    12    19     40     54       853
## 13     13  2015     1    13     7     55      6       924
## 14     14  2015     1    14    13     23     15       923
## 15     15  2015     1    15    14     51     17       941
## 16     16  2015     1    16    21     11     24       702
## 17     17  2015     1    17     0     32      7       854
## 18     18  2015     1    18     9     31     32       851
## 19     19  2015     1    19     4     56     41       837
## 20     20  2015     1    20    20     24     22       844</code></pre>
<p>As we can see, the dataset Friends visits contains information about all of the visits from friends that the host(s) received in the year 2015. The information includes date and time of each friend’s visit as well as the time that they left.</p>
<p>Right now, the none of the columns are recognized as date or time in R because all of the information are scattered across multiple columns. In addition, the column “Left_time” also clumps together the hours and minutes into one incoherent number. For this specific column, we need to clearly identify the hour and minute so that R can recognize it as containing date/time.</p>
<p>But before we jump even further into this tutorial, let’s actually filter out information from this dataset. Let’s say we only want to retain visits that are before 9 PM.</p>
<div class="sourceCode" id="cb421"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb421-1"><a href="date-time-data-with-lubridate.html#cb421-1" aria-hidden="true" tabindex="-1"></a>visits <span class="ot">&lt;-</span> <span class="fu">filter</span>(visits, Hour <span class="sc">&lt;</span> <span class="dv">21</span>)</span></code></pre></div>
<p>Now, let’s check our dataset again.</p>
<div class="sourceCode" id="cb422"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb422-1"><a href="date-time-data-with-lubridate.html#cb422-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(visits)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 8
##   Friend  Year Month   Day  Hour Minute Second Left_time
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;
## 1      1  2015     1     1    19      4     22       830
## 2      2  2015     1     2     9     20     19       850
## 3      4  2015     1     4     9     22     51      1004
## 4      5  2015     1     5    18      1     16       812
## 5      6  2015     1     6     5     59      2       740
## 6      7  2015     1     7     9     45     55       913</code></pre>
</div>
<div id="creating-datetime-data" class="section level2" number="7.5">
<h2><span class="header-section-number">7.5</span> Creating Date/Time Data</h2>
<p>Date/time data are data tht conveys information about, you guessed it, date and/or time! There are three relevant data types when we talk about date/time data:
1. <strong>Date</strong> - only has the date (e.g. 2020-05-15)
2. <strong>Time</strong> - only has the time (e.g. 20:45:00)
3. <strong>Datetime</strong> - has both the date and time (e.g. 2020-05-15 20:45:00)</p>
<p>Now that we know the different types of date/time data, know that there are also several ways for us to create date/time data: we can create them from raw <strong>strings</strong>, from an <strong>existing date/time data</strong>, or from a <strong>dataset</strong>.</p>
<div id="strings-1" class="section level3" number="7.5.1">
<h3><span class="header-section-number">7.5.1</span> Strings</h3>
<p>Firstly, we can use <code>ymd()</code> with a quoted string to create a new date/time data.</p>
<div class="sourceCode" id="cb424"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb424-1"><a href="date-time-data-with-lubridate.html#cb424-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ymd</span>(<span class="st">&quot;2021-06-20&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2021-06-20&quot;</code></pre>
<p>We can also change the order of the letters in <code>ymd()</code> to match which information came first (year, month, or day). For example, R reads <code>ymd()</code> as “year, month, date” and <code>dmy()</code> as “day, month, year.”</p>
<div class="sourceCode" id="cb426"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb426-1"><a href="date-time-data-with-lubridate.html#cb426-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dmy</span>(<span class="st">&quot;15 Feb, 2010&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2010-02-15&quot;</code></pre>
<p>Similarly, <code>mdy()</code> is also an option. In the example below, the string is just a series of numbers that R will reads as month, day, year.</p>
<div class="sourceCode" id="cb428"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb428-1"><a href="date-time-data-with-lubridate.html#cb428-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mdy</span>(<span class="st">&quot;07082016&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2016-07-08&quot;</code></pre>
<p>If we do choose to only write a series of number, then our string can be unquoted as well. R will still be able to identify that this is a string and will read it accordingly!</p>
<div class="sourceCode" id="cb430"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb430-1"><a href="date-time-data-with-lubridate.html#cb430-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mdy</span>(<span class="dv">07082016</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2016-07-08&quot;</code></pre>
<p>In addition, we can also generate hour, minute, and second information by using <code>ymd_hms()</code>. Different than the functions above, we cannot change the order of “hms.”</p>
<div class="sourceCode" id="cb432"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb432-1"><a href="date-time-data-with-lubridate.html#cb432-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ymd_hms</span>(<span class="st">&quot;2021-06-20-5-49-34&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2021-06-20 05:49:34 UTC&quot;</code></pre>
<p>In R, the default time zone is Coordinated Universal Time, or UTC for short. But we can also change the time zone of our date/time data by using the <code>tz</code> argument like so:</p>
<div class="sourceCode" id="cb434"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb434-1"><a href="date-time-data-with-lubridate.html#cb434-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ymd_hms</span>(<span class="st">&quot;2021-06-20-5-49-34&quot;</span>, <span class="at">tz =</span> <span class="st">&quot;America/Vancouver&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2021-06-20 05:49:34 PDT&quot;</code></pre>
<div class="sourceCode" id="cb436"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb436-1"><a href="date-time-data-with-lubridate.html#cb436-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ymd_hms</span>(<span class="st">&quot;2021-06-20-5-49-34&quot;</span>, <span class="at">tz =</span> <span class="st">&quot;Etc/GMT+7&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2021-06-20 05:49:34 -07&quot;</code></pre>
<p>To check the full list of time zones that R recognizes, we can use the function <code>OlsonNames()</code>.</p>
<div class="sourceCode" id="cb438"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb438-1"><a href="date-time-data-with-lubridate.html#cb438-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">OlsonNames</span>(), <span class="dv">10</span>)</span></code></pre></div>
<pre><code>##  [1] &quot;Africa/Abidjan&quot;     &quot;Africa/Accra&quot;       &quot;Africa/Addis_Ababa&quot;
##  [4] &quot;Africa/Algiers&quot;     &quot;Africa/Asmara&quot;      &quot;Africa/Asmera&quot;     
##  [7] &quot;Africa/Bamako&quot;      &quot;Africa/Bangui&quot;      &quot;Africa/Banjul&quot;     
## [10] &quot;Africa/Bissau&quot;</code></pre>
<p>We can also use the following code to check what our current time zone is.</p>
<div class="sourceCode" id="cb440"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb440-1"><a href="date-time-data-with-lubridate.html#cb440-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Sys.timezone</span>()</span></code></pre></div>
<pre><code>## [1] &quot;America/Los_Angeles&quot;</code></pre>
<p>If after running the code above and R returns NA or UTC for you, it means the software cannot correctly identify where we are. For this, we can tell R directly what our time zone is. For example, if we are in Vancouver, BC, Canada right now, we would write the following code:</p>
<div class="sourceCode" id="cb442"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb442-1"><a href="date-time-data-with-lubridate.html#cb442-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Sys.setenv</span>(<span class="at">TZ =</span> <span class="st">&quot;America/Vancouver&quot;</span>)</span></code></pre></div>
<p>To confirm if the correct time zone has been set, we can use the functions <code>today()</code> or <code>now()</code>.</p>
<div class="sourceCode" id="cb443"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb443-1"><a href="date-time-data-with-lubridate.html#cb443-1" aria-hidden="true" tabindex="-1"></a><span class="fu">today</span>()</span></code></pre></div>
<pre><code>## [1] &quot;2021-09-05&quot;</code></pre>
<div class="sourceCode" id="cb445"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb445-1"><a href="date-time-data-with-lubridate.html#cb445-1" aria-hidden="true" tabindex="-1"></a><span class="fu">now</span>()</span></code></pre></div>
<pre><code>## [1] &quot;2021-09-05 14:17:25 PDT&quot;</code></pre>
</div>
<div id="try-it-yourself-7.17.1" class="section level3 unnumbered">
<h3><a href="appendix-exercise-solutions.html#section-28">Try it yourself 7.1</a></h3>
<p>After running the <code>today()</code> and <code>now()</code> codes above, what do you see?</p>
<p>Try to also change the time zone to where you are or to something else. Now what do you see when you run <code>today()</code> and <code>now()</code>?</p>
<div id="do-questions-1-3-of-the-quiz-now-2" class="section level4 unnumbered">
<h4>DO QUESTIONS 1-3 OF THE QUIZ NOW</h4>
<ul>
<li><p>Which of the following is a date data?</p></li>
<li><p>What data type is this: 2017-09-19 19:00:00?</p></li>
<li><p>What is different about the outputs’ data types of <code>today()</code> and <code>now()</code>? (Select all that apply)</p></li>
</ul>
</div>
</div>
<div id="existing-datetime-data" class="section level3" number="7.5.2">
<h3><span class="header-section-number">7.5.2</span> Existing Date/Time Data</h3>
<p>You may have recognized that while <code>today()</code> gives us only the current date, <code>now()</code> gives us both the date and time of our current location - in this case, America/Vancouver.</p>
<p>We can actually convert date data to datetime and vice versa using <code>as_datetime()</code> and <code>as_date()</code>.</p>
<div class="sourceCode" id="cb447"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb447-1"><a href="date-time-data-with-lubridate.html#cb447-1" aria-hidden="true" tabindex="-1"></a><span class="do">## from date to datetime</span></span>
<span id="cb447-2"><a href="date-time-data-with-lubridate.html#cb447-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb447-3"><a href="date-time-data-with-lubridate.html#cb447-3" aria-hidden="true" tabindex="-1"></a><span class="fu">as_datetime</span>(<span class="fu">today</span>())</span></code></pre></div>
<pre><code>## [1] &quot;2021-09-05 UTC&quot;</code></pre>
<div class="sourceCode" id="cb449"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb449-1"><a href="date-time-data-with-lubridate.html#cb449-1" aria-hidden="true" tabindex="-1"></a><span class="do">## from datetime to date</span></span>
<span id="cb449-2"><a href="date-time-data-with-lubridate.html#cb449-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb449-3"><a href="date-time-data-with-lubridate.html#cb449-3" aria-hidden="true" tabindex="-1"></a><span class="fu">as_date</span>(<span class="fu">now</span>())</span></code></pre></div>
<pre><code>## [1] &quot;2021-09-05&quot;</code></pre>
</div>
<div id="dataset" class="section level3" number="7.5.3">
<h3><span class="header-section-number">7.5.3</span> Dataset</h3>
<p>Lastly, we can also create date/time data using a dataset. For this section, we will be using the flights dataset from the nycflights13 package that we have briefly explored previously.</p>
<p>Let’s quickly look at our data again.</p>
<div class="sourceCode" id="cb451"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb451-1"><a href="date-time-data-with-lubridate.html#cb451-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(visits)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 8
##   Friend  Year Month   Day  Hour Minute Second Left_time
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;
## 1      1  2015     1     1    19      4     22       830
## 2      2  2015     1     2     9     20     19       850
## 3      4  2015     1     4     9     22     51      1004
## 4      5  2015     1     5    18      1     16       812
## 5      6  2015     1     6     5     59      2       740
## 6      7  2015     1     7     9     45     55       913</code></pre>
<p>As we can see, all of these columns contain data regarding date and time.</p>
<p>Unfortunately, because the information about datetime is divided up into different columns, R does not recognize it as date/time data. What we need to do is combine and convert all of these columns into datetime. To do this, we can use the function <code>make_datetime()</code>.</p>
<div class="sourceCode" id="cb453"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb453-1"><a href="date-time-data-with-lubridate.html#cb453-1" aria-hidden="true" tabindex="-1"></a>visits_datetime <span class="ot">&lt;-</span> visits <span class="sc">%&gt;%</span></span>
<span id="cb453-2"><a href="date-time-data-with-lubridate.html#cb453-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Visit_time =</span> <span class="fu">make_datetime</span>(Year, Month, Day, Hour, Minute))</span></code></pre></div>
<div class="sourceCode" id="cb454"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb454-1"><a href="date-time-data-with-lubridate.html#cb454-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(visits_datetime)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 9
##   Friend  Year Month   Day  Hour Minute Second Left_time Visit_time         
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt; &lt;dttm&gt;             
## 1      1  2015     1     1    19      4     22       830 2015-01-01 19:04:00
## 2      2  2015     1     2     9     20     19       850 2015-01-02 09:20:00
## 3      4  2015     1     4     9     22     51      1004 2015-01-04 09:22:00
## 4      5  2015     1     5    18      1     16       812 2015-01-05 18:01:00
## 5      6  2015     1     6     5     59      2       740 2015-01-06 05:59:00
## 6      7  2015     1     7     9     45     55       913 2015-01-07 09:45:00</code></pre>
<p>Now if we look at our new column <code>Visit_time</code>, we should see that all of the information that we have mentioned in our code have been combined into one single value that takes the form of datetime!</p>
<p>So we know how to combine information of different columns to form one cohesive one, what about the Left_time colum? How can we turn values like 1951 into 19:51:00? Once again, <code>make_datetime()</code> is the answer!</p>
<p>But first, we need to quickly create a new function that will help us make this process easier. This new function will retain information about the year, month, and date as well as divide the time into hours and minutes.</p>
<div class="sourceCode" id="cb456"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb456-1"><a href="date-time-data-with-lubridate.html#cb456-1" aria-hidden="true" tabindex="-1"></a>make_datetime_new <span class="ot">&lt;-</span> <span class="cf">function</span>(year, month, day, time) {</span>
<span id="cb456-2"><a href="date-time-data-with-lubridate.html#cb456-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">make_datetime</span>(year, month, day, time <span class="sc">%/%</span> <span class="dv">100</span>, time <span class="sc">%%</span> <span class="dv">100</span>)</span>
<span id="cb456-3"><a href="date-time-data-with-lubridate.html#cb456-3" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<div id="do-question-4-of-the-quiz-now-2" class="section level4 unnumbered">
<h4>DO QUESTION 4 OF THE QUIZ NOW</h4>
<ul>
<li><strong>REVIEW:</strong> What is the difference between %/% and %%?</li>
</ul>
<p>Here, we are telling R to write a new <code>make_datetime()</code> function named <code>make_datetime_new()</code>. Our new function then has 5 arguments, the year, the month, the day, the time %/% 100, and the time %% 100. The last two arguments will give us the hour and minutes of the day. In other words, 830 %/% 100 = 8 and 830 %% 100 is 30, so combined, 830 becomes 8:30!</p>
<p>Now if we apply this new function to our flights_datetime’s arr_time column, we should see the new “arr_time” column with the arrival time of flights in date/time form.</p>
<div class="sourceCode" id="cb457"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb457-1"><a href="date-time-data-with-lubridate.html#cb457-1" aria-hidden="true" tabindex="-1"></a>Friends_visits <span class="ot">&lt;-</span> visits_datetime <span class="sc">%&gt;%</span> </span>
<span id="cb457-2"><a href="date-time-data-with-lubridate.html#cb457-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Left_time =</span> <span class="fu">make_datetime_new</span>(Year, Month, Day, Left_time))</span></code></pre></div>
<div class="sourceCode" id="cb458"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb458-1"><a href="date-time-data-with-lubridate.html#cb458-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Friends_visits)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 9
##   Friend  Year Month   Day  Hour Minute Second Left_time          
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dttm&gt;             
## 1      1  2015     1     1    19      4     22 2015-01-01 08:30:00
## 2      2  2015     1     2     9     20     19 2015-01-02 08:50:00
## 3      4  2015     1     4     9     22     51 2015-01-04 10:04:00
## 4      5  2015     1     5    18      1     16 2015-01-05 08:12:00
## 5      6  2015     1     6     5     59      2 2015-01-06 07:40:00
## 6      7  2015     1     7     9     45     55 2015-01-07 09:13:00
## # ... with 1 more variable: Visit_time &lt;dttm&gt;</code></pre>
<p>Another simpler way to use <code>make_datetime()</code> is to insert the numerical values of the year, month, day, and time directly.</p>
<div class="sourceCode" id="cb460"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb460-1"><a href="date-time-data-with-lubridate.html#cb460-1" aria-hidden="true" tabindex="-1"></a><span class="fu">make_datetime</span>(<span class="dv">2014</span>, <span class="dv">8</span>, <span class="dv">22</span>, <span class="dv">9</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2014-08-22 09:00:00 UTC&quot;</code></pre>
</div>
<div id="do-question-5-of-the-quiz-now-3" class="section level4 unnumbered">
<h4>DO QUESTION 5 OF THE QUIZ NOW</h4>
<ul>
<li>Using the Friends_visits data frame, which of the following code will give us a new column named “Year_Month” that only has information of the year and month of each friend visit?</li>
</ul>
</div>
</div>
<div id="functions-debunked-20" class="section level3 unnumbered">
<h3>Functions Debunked</h3>
<p><strong><a href="https://lubridate.tidyverse.org/reference/make_datetime.html">make_datetime()</a></strong> can be used to create new datetime data. The arguments are as follows:</p>
<p>make_datetime(<strong>Values of Year</strong>, <strong>Values of Month</strong>, <strong>Values of Day</strong>, <strong>Values of Hour</strong>, <strong>Values of Minute</strong>, <strong>Values of Second</strong>)</p>
<p><strong>For example:</strong></p>
<ul>
<li><p>Combine columns of a dataset: <code>flights_datetime %&gt;% make_datetime(year, month, day, hour, minute)</code></p></li>
<li><p>Insert values directly: <code>make_datetime(2014, 8, 22, 9)</code></p></li>
</ul>
</div>
<div id="try-it-yourself-7.27.2" class="section level3 unnumbered">
<h3><a href="appendix-exercise-solutions.html#section-29">Try it yourself 7.2</a></h3>
<p>Try creating a new column named “Day_visit” that only contains information of the Year, Month, and Day columns using the Friends_visits dataframe that we just created.</p>
</div>
</div>
<div id="retrieving-information-from-datetime-data" class="section level2" number="7.6">
<h2><span class="header-section-number">7.6</span> Retrieving Information from Date/Time Data</h2>
<p>We have learned how to create date/time data, but how do we retrieve information from the date/time data that we created? Hopefully, by the end of this section, we would be able to answer this question!</p>
<p>Let’s first create a simple datetime value from a string using <code>ymd_hms()</code>. And let’s also use the column “Visit_time” of our Friends_visits data frame.</p>
<div class="sourceCode" id="cb462"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb462-1"><a href="date-time-data-with-lubridate.html#cb462-1" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">ymd_hms</span>(<span class="st">&quot;2020-04-19 09:45:00&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb463"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb463-1"><a href="date-time-data-with-lubridate.html#cb463-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Friends_visits<span class="sc">$</span>Visit_time)</span></code></pre></div>
<pre><code>## [1] &quot;2015-01-01 19:04:00 UTC&quot; &quot;2015-01-02 09:20:00 UTC&quot;
## [3] &quot;2015-01-04 09:22:00 UTC&quot; &quot;2015-01-05 18:01:00 UTC&quot;
## [5] &quot;2015-01-06 05:59:00 UTC&quot; &quot;2015-01-07 09:45:00 UTC&quot;</code></pre>
<div id="year" class="section level3" number="7.6.1">
<h3><span class="header-section-number">7.6.1</span> Year</h3>
<p>Now, if we want to know the year of our datetime value, we can use the function <code>year()</code> with the name of our datetime variable between the <code>()</code>.</p>
<div class="sourceCode" id="cb465"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb465-1"><a href="date-time-data-with-lubridate.html#cb465-1" aria-hidden="true" tabindex="-1"></a><span class="fu">year</span>(DT)</span></code></pre></div>
<pre><code>## [1] 2020</code></pre>
<div class="sourceCode" id="cb467"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb467-1"><a href="date-time-data-with-lubridate.html#cb467-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(</span>
<span id="cb467-2"><a href="date-time-data-with-lubridate.html#cb467-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">year</span>(Friends_visits<span class="sc">$</span>Visit_time)</span>
<span id="cb467-3"><a href="date-time-data-with-lubridate.html#cb467-3" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div>
<pre><code>## [1] 2015 2015 2015 2015 2015 2015</code></pre>
<p>The reason why the outputs to <code>year(Friends_visits$Visit_time)</code> are all 2015s is because if we look at the first 6 records of the columns “Visit_time,” all year values are 2015!</p>
<p>Similarly, we can also use the function <code>yday()</code> to find out what day of the year our datetime value falls into. For example, April 19 is the <strong>110th</strong> day of the year.</p>
<div class="sourceCode" id="cb469"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb469-1"><a href="date-time-data-with-lubridate.html#cb469-1" aria-hidden="true" tabindex="-1"></a><span class="fu">yday</span>(DT)</span></code></pre></div>
<pre><code>## [1] 110</code></pre>
<p>Using the same function on our Friends_visits data frame, we can see that the first 6 records of the column “Visit_time” contains the first, second, fourth, fifth, sixth, and seventh day of the year.</p>
<div class="sourceCode" id="cb471"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb471-1"><a href="date-time-data-with-lubridate.html#cb471-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(</span>
<span id="cb471-2"><a href="date-time-data-with-lubridate.html#cb471-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">yday</span>(Friends_visits<span class="sc">$</span>Visit_time)</span>
<span id="cb471-3"><a href="date-time-data-with-lubridate.html#cb471-3" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div>
<pre><code>## [1] 1 2 4 5 6 7</code></pre>
</div>
<div id="month" class="section level3" number="7.6.2">
<h3><span class="header-section-number">7.6.2</span> Month</h3>
<p><code>mday()</code> is similar to <code>yday()</code> except it gives us what day of the month our datetime value falls into. In this case, “4-19” is the <strong>19th</strong> day of April!</p>
<div class="sourceCode" id="cb473"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb473-1"><a href="date-time-data-with-lubridate.html#cb473-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mday</span>(DT)</span></code></pre></div>
<pre><code>## [1] 19</code></pre>
<p>What days of the month do the first 6 records of Visit_time contain?</p>
<div class="sourceCode" id="cb475"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb475-1"><a href="date-time-data-with-lubridate.html#cb475-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(</span>
<span id="cb475-2"><a href="date-time-data-with-lubridate.html#cb475-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mday</span>(Friends_visits<span class="sc">$</span>Visit_time)</span>
<span id="cb475-3"><a href="date-time-data-with-lubridate.html#cb475-3" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div>
<pre><code>## [1] 1 2 4 5 6 7</code></pre>
<p>At this point, we should already have figured out the pattern, so <code>month()</code> will give us the month of our datetime value, normally, with a numerical output. If we want to convert month from a numerical “4” to “Apr,” we would add the <code>label</code> argument like so:</p>
<div class="sourceCode" id="cb477"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb477-1"><a href="date-time-data-with-lubridate.html#cb477-1" aria-hidden="true" tabindex="-1"></a><span class="fu">month</span>(DT, <span class="at">label =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] Apr
## 12 Levels: Jan &lt; Feb &lt; Mar &lt; Apr &lt; May &lt; Jun &lt; Jul &lt; Aug &lt; Sep &lt; ... &lt; Dec</code></pre>
<div class="sourceCode" id="cb479"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb479-1"><a href="date-time-data-with-lubridate.html#cb479-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(</span>
<span id="cb479-2"><a href="date-time-data-with-lubridate.html#cb479-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">month</span>(Friends_visits<span class="sc">$</span>Visit_time, <span class="at">label =</span> <span class="cn">TRUE</span>)</span>
<span id="cb479-3"><a href="date-time-data-with-lubridate.html#cb479-3" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div>
<pre><code>## [1] Jan Jan Jan Jan Jan Jan
## 12 Levels: Jan &lt; Feb &lt; Mar &lt; Apr &lt; May &lt; Jun &lt; Jul &lt; Aug &lt; Sep &lt; ... &lt; Dec</code></pre>
</div>
<div id="week" class="section level3" number="7.6.3">
<h3><span class="header-section-number">7.6.3</span> Week</h3>
<p><code>wday()</code> will give us what day of the week our datetime value falls into. Similarly, we can use <code>label</code> to change numerical values to “Mon,” “Tues,” “Wed,” etc. If we want the full “Monday” instead of just “Mon,” we would add the <code>abbr</code> argument like so:</p>
<div class="sourceCode" id="cb481"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb481-1"><a href="date-time-data-with-lubridate.html#cb481-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wday</span>(DT, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] Sunday
## 7 Levels: Sunday &lt; Monday &lt; Tuesday &lt; Wednesday &lt; Thursday &lt; ... &lt; Saturday</code></pre>
<div class="sourceCode" id="cb483"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb483-1"><a href="date-time-data-with-lubridate.html#cb483-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(</span>
<span id="cb483-2"><a href="date-time-data-with-lubridate.html#cb483-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">wday</span>(Friends_visits<span class="sc">$</span>Visit_time, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">FALSE</span>)</span>
<span id="cb483-3"><a href="date-time-data-with-lubridate.html#cb483-3" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div>
<pre><code>## [1] Thursday  Friday    Sunday    Monday    Tuesday   Wednesday
## 7 Levels: Sunday &lt; Monday &lt; Tuesday &lt; Wednesday &lt; Thursday &lt; ... &lt; Saturday</code></pre>
</div>
<div id="try-it-yourself-7.37.3" class="section level3 unnumbered">
<h3><a href="appendix-exercise-solutions.html#section-30">Try it yourself 7.3</a></h3>
<p>Using the functions introduced above, solve the following questions:
1. What day of the week is April 2, 2014?
2. What day of the year is 2017-09-15?
3. What day of the month is 20190830?
4. Find the months of the last 11 records of the column Visit_hour.</p>
</div>
<div id="plotting-retrieved-information" class="section level3" number="7.6.4">
<h3><span class="header-section-number">7.6.4</span> Plotting Retrieved Information</h3>
<p>Let’s try to aply the functions that we just learned above by retrieving information from the Friends_visits dataset that we previously created.</p>
<p>Here is the dataset again:</p>
<div class="sourceCode" id="cb485"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb485-1"><a href="date-time-data-with-lubridate.html#cb485-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Friends_visits)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 9
##   Friend  Year Month   Day  Hour Minute Second Left_time          
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dttm&gt;             
## 1      1  2015     1     1    19      4     22 2015-01-01 08:30:00
## 2      2  2015     1     2     9     20     19 2015-01-02 08:50:00
## 3      4  2015     1     4     9     22     51 2015-01-04 10:04:00
## 4      5  2015     1     5    18      1     16 2015-01-05 08:12:00
## 5      6  2015     1     6     5     59      2 2015-01-06 07:40:00
## 6      7  2015     1     7     9     45     55 2015-01-07 09:13:00
## # ... with 1 more variable: Visit_time &lt;dttm&gt;</code></pre>
<p>Let’s say we want to plot a bar graph to show how many visits each month in 2015 the hosts have using the Visit_time column. First we want to extract the months from the Visit_time values. After that, we want to place the extracted months in the “month” column.</p>
<p>To complete our goals, we need to use both <code>mutate()</code> and <code>month()</code> like so:</p>
<div class="sourceCode" id="cb487"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb487-1"><a href="date-time-data-with-lubridate.html#cb487-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(</span>
<span id="cb487-2"><a href="date-time-data-with-lubridate.html#cb487-2" aria-hidden="true" tabindex="-1"></a>Friends_visits <span class="sc">%&gt;%</span> </span>
<span id="cb487-3"><a href="date-time-data-with-lubridate.html#cb487-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Month =</span> <span class="fu">month</span>(Visit_time, <span class="at">label =</span> <span class="cn">TRUE</span>))</span>
<span id="cb487-4"><a href="date-time-data-with-lubridate.html#cb487-4" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div>
<pre><code>## # A tibble: 6 x 9
##   Friend  Year Month   Day  Hour Minute Second Left_time          
##    &lt;dbl&gt; &lt;dbl&gt; &lt;ord&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dttm&gt;             
## 1      1  2015 Jan       1    19      4     22 2015-01-01 08:30:00
## 2      2  2015 Jan       2     9     20     19 2015-01-02 08:50:00
## 3      4  2015 Jan       4     9     22     51 2015-01-04 10:04:00
## 4      5  2015 Jan       5    18      1     16 2015-01-05 08:12:00
## 5      6  2015 Jan       6     5     59      2 2015-01-06 07:40:00
## 6      7  2015 Jan       7     9     45     55 2015-01-07 09:13:00
## # ... with 1 more variable: Visit_time &lt;dttm&gt;</code></pre>
<p>We should be able to see that all of the “1”s under the month (second) column, have successfully turned into “Jan.”</p>
<p>Finally, all we need is a <code>ggplot()</code> canvas and a <code>geom_bar()</code> function! <strong>(Notice the transition from pipe <code>%&gt;%</code> to <code>+</code>).</strong></p>
<div class="sourceCode" id="cb489"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb489-1"><a href="date-time-data-with-lubridate.html#cb489-1" aria-hidden="true" tabindex="-1"></a>Friends_visits <span class="sc">%&gt;%</span> </span>
<span id="cb489-2"><a href="date-time-data-with-lubridate.html#cb489-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Month =</span> <span class="fu">month</span>(Visit_time, <span class="at">label =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb489-3"><a href="date-time-data-with-lubridate.html#cb489-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(Month)) <span class="sc">+</span></span>
<span id="cb489-4"><a href="date-time-data-with-lubridate.html#cb489-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>()</span></code></pre></div>
<p><img src="intro2R_files/figure-html/unnamed-chunk-265-1.png" width="672" /></p>
<div id="do-question-6-of-the-quiz-now-2" class="section level4 unnumbered">
<h4>DO QUESTION 6 OF THE QUIZ NOW</h4>
<ul>
<li>What is the difference between <code>%&gt;%</code> and <code>+</code>? (Select all that apply)</li>
</ul>
</div>
</div>
<div id="try-it-yourself-7.47.4" class="section level3 unnumbered">
<h3><a href="appendix-exercise-solutions.html#section-31">Try it yourself 7.4</a></h3>
<p>Using the same Friends_visit dataset, create a similar graph as above but the x-axis is days of the week. In other words, create a bar graph that shows how many visits there are in each day of the week.</p>
</div>
</div>
<div id="updating-plotting-datetime-data" class="section level2" number="7.7">
<h2><span class="header-section-number">7.7</span> Updating &amp; Plotting Date/Time Data</h2>
<div id="update" class="section level3" number="7.7.1">
<h3><span class="header-section-number">7.7.1</span> Update</h3>
<p>To modify or update a piece of date/time data, we would use <code>update()</code>. Updating a date/time data can mean changing it completely:</p>
<div class="sourceCode" id="cb490"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb490-1"><a href="date-time-data-with-lubridate.html#cb490-1" aria-hidden="true" tabindex="-1"></a>(DT <span class="ot">&lt;-</span> <span class="fu">ymd_hms</span>(<span class="st">&quot;2020-04-19 09:45:00&quot;</span>))</span></code></pre></div>
<pre><code>## [1] &quot;2020-04-19 09:45:00 UTC&quot;</code></pre>
<div class="sourceCode" id="cb492"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb492-1"><a href="date-time-data-with-lubridate.html#cb492-1" aria-hidden="true" tabindex="-1"></a><span class="fu">update</span>(DT, <span class="at">year =</span> <span class="dv">2021</span>, <span class="at">month =</span> <span class="dv">6</span>, <span class="at">day =</span> <span class="dv">21</span>, <span class="at">hour =</span> <span class="dv">9</span>, <span class="at">minute =</span> <span class="dv">13</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2021-06-21 09:13:00 UTC&quot;</code></pre>
<p>The cool thing about the <code>update()</code> function is that it will automatically adjust the date and time if the value that we want to change our current date/time to is too large. For example, April only has 30 days. Now look what happens when we try to update our date to 2020-04-31.</p>
<div class="sourceCode" id="cb494"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb494-1"><a href="date-time-data-with-lubridate.html#cb494-1" aria-hidden="true" tabindex="-1"></a>DT <span class="sc">%&gt;%</span></span>
<span id="cb494-2"><a href="date-time-data-with-lubridate.html#cb494-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">update</span>(<span class="at">day =</span> <span class="dv">31</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2020-05-01 09:45:00 UTC&quot;</code></pre>
<p><code>update()</code> automatically adjusts it to May 1st instead because April 31st does not exist!</p>
</div>
<div id="try-it-yourself-7.57.5" class="section level3 unnumbered">
<h3><a href="appendix-exercise-solutions.html#section-32">Try it yourself 7.5</a></h3>
<p>Try to update our month to 13. What happened to our date/time? What is the output?</p>
<p><strong><a href="https://lubridate.tidyverse.org/reference/DateTimeUpdate.html">update()</a></strong> can be used to update existing datetime data. The arguments are as follows:</p>
<p>update(</p>
<blockquote>
<p>year = <strong>VALUES OF YEAR,</strong></p>
</blockquote>
<blockquote>
<p>month = <strong>VALUES OF MONTH,</strong></p>
</blockquote>
<blockquote>
<p>day OR mday OR yday = <strong>VALUES OF DAY,</strong></p>
</blockquote>
<blockquote>
<p>hour = <strong>VALUES OF HOUR,</strong></p>
</blockquote>
<blockquote>
<p>minute = <strong>VALUES OF MINUTE,</strong></p>
</blockquote>
<blockquote>
<p>second = <strong>VALUES OF SECOND</strong></p>
</blockquote>
<p>)</p>
<p><strong>For example:</strong>
* <code>update(DT, year = 2021, month = 6, day = 21, hour = 9, minute = 13)</code>
* <code>update(ymd_hms("2020-04-19 09:45:00"), year = 2021, month = 6, day = 21, hour = 9, minute = 13)</code></p>
</div>
<div id="plotting-datetime" class="section level3" number="7.7.2">
<h3><span class="header-section-number">7.7.2</span> Plotting Date/Time</h3>
<p>So far, we have learned how to plot graphs with date data type, such as month and weekday, in the x-axis. But what if we want to plot our time data in the x-axis instead? Although it sounds simple, plotting time data may be a bit harder than it seems because there is no function in the lubridate package that allows us to only retain time data. In other words, there is no <code>hms()</code> function… in lubridate.</p>
<p>To loophole around this issue, we can use <code>update()</code>! Basically, we want to update all dates in our data to the same date, let’s say January 1 2015, so that when we plot the graph, the graph will be representative of friends visits in each hour. It will make more sense when we start plotting the graph.</p>
<p>Let’s check the dataset again before we start plotting.</p>
<div class="sourceCode" id="cb496"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb496-1"><a href="date-time-data-with-lubridate.html#cb496-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Friends_visits)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 9
##   Friend  Year Month   Day  Hour Minute Second Left_time          
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dttm&gt;             
## 1      1  2015     1     1    19      4     22 2015-01-01 08:30:00
## 2      2  2015     1     2     9     20     19 2015-01-02 08:50:00
## 3      4  2015     1     4     9     22     51 2015-01-04 10:04:00
## 4      5  2015     1     5    18      1     16 2015-01-05 08:12:00
## 5      6  2015     1     6     5     59      2 2015-01-06 07:40:00
## 6      7  2015     1     7     9     45     55 2015-01-07 09:13:00
## # ... with 1 more variable: Visit_time &lt;dttm&gt;</code></pre>
<p>Recall that in this dataset, we have already converted the Visit_time column to contain data in the date/time form. However, right now, R recognizes this column using date AND time, but we only want R to distinguish the different times for our graph. So, as we have discussed before, we want to trick R into thinking that all 365 records are of the same date, just different times. To do this, we use <code>update()</code>.</p>
<div class="sourceCode" id="cb498"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb498-1"><a href="date-time-data-with-lubridate.html#cb498-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(</span>
<span id="cb498-2"><a href="date-time-data-with-lubridate.html#cb498-2" aria-hidden="true" tabindex="-1"></a>    Friends_visits <span class="sc">%&gt;%</span></span>
<span id="cb498-3"><a href="date-time-data-with-lubridate.html#cb498-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Visit_hour =</span> <span class="fu">update</span>(Visit_time, <span class="at">yday =</span> <span class="dv">1</span>))</span>
<span id="cb498-4"><a href="date-time-data-with-lubridate.html#cb498-4" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div>
<pre><code>## # A tibble: 6 x 10
##   Friend  Year Month   Day  Hour Minute Second Left_time          
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dttm&gt;             
## 1      1  2015     1     1    19      4     22 2015-01-01 08:30:00
## 2      2  2015     1     2     9     20     19 2015-01-02 08:50:00
## 3      4  2015     1     4     9     22     51 2015-01-04 10:04:00
## 4      5  2015     1     5    18      1     16 2015-01-05 08:12:00
## 5      6  2015     1     6     5     59      2 2015-01-06 07:40:00
## 6      7  2015     1     7     9     45     55 2015-01-07 09:13:00
## # ... with 2 more variables: Visit_time &lt;dttm&gt;, Visit_hour &lt;dttm&gt;</code></pre>
<p>Now if we look at the new “Visit_hour” column, all records should have the same date: 2015-01-01. Perfect!</p>
<p>The next step is to actually plot this on a frequency polygon like so:</p>
<div class="sourceCode" id="cb500"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb500-1"><a href="date-time-data-with-lubridate.html#cb500-1" aria-hidden="true" tabindex="-1"></a> Friends_visits <span class="sc">%&gt;%</span></span>
<span id="cb500-2"><a href="date-time-data-with-lubridate.html#cb500-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Visit_hour =</span> <span class="fu">update</span>(Visit_time, <span class="at">yday =</span> <span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb500-3"><a href="date-time-data-with-lubridate.html#cb500-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(Visit_hour)) <span class="sc">+</span></span>
<span id="cb500-4"><a href="date-time-data-with-lubridate.html#cb500-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_freqpoly</span>(<span class="at">binwidth =</span> <span class="dv">3600</span>)</span></code></pre></div>
<p><img src="intro2R_files/figure-html/unnamed-chunk-271-1.png" width="672" /></p>
<p>This graph is a bit tricky to read because even though the x-axis says that all data points are within Jan 01, we know this is not true - the data displayed are from Jan 01 to Dec 31! Again, the reason why our x-axis is labelled as Jan 01 is because we have tricked R into thinking that all data points are of the same date so that our graph can plot the number of friend visits depending on times.</p>
<p>What information can you conclude from the graph above? Around what timeframe do our host(s) receive the most friends visits?</p>
<p>Note that each binwidth (i.e. binwidth = 1) is equal to one second. So <code>binwidth = 3600</code> means we are clumping all flights within each 60 minutes (1 hour) together into one single data point in our frequency polygon.</p>
</div>
<div id="try-it-yourself-7.67.6" class="section level3 unnumbered">
<h3><a href="appendix-exercise-solutions.html#section-33">Try it yourself 7.6</a></h3>
<p>Recreate the frequency polygon above but change the binwidth so that all flights within each 30 minutes are clumped into one single data point. How do the graphs differ? Can you think of a few scenarios where one would be preferred?</p>
<div id="do-question-7-of-the-quiz-now-1" class="section level4 unnumbered">
<h4>DO QUESTION 7 OF THE QUIZ NOW</h4>
<ul>
<li>What should the binwidth be if we want to have each data point to represent a separate 2 hour interval?</li>
</ul>
</div>
<div id="hms-package" class="section level4" number="7.7.2.1">
<h4><span class="header-section-number">7.7.2.1</span> hms package</h4>
<p>There is actually another package in R (and also part of the tidyverse core) that deals with time data specifically: hms. This function provides an alternative to the ggplot code we just wrote above.</p>
<p>We will not go over this package or function in detail in this tutorial. You can explore hms more via this <a href="https://cran.r-project.org/web/packages/hms/hms.pdf">link</a>.</p>
<div class="sourceCode" id="cb501"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb501-1"><a href="date-time-data-with-lubridate.html#cb501-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&quot;hms&quot;)</span></span>
<span id="cb501-2"><a href="date-time-data-with-lubridate.html#cb501-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(hms)</span></code></pre></div>
<div class="sourceCode" id="cb502"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb502-1"><a href="date-time-data-with-lubridate.html#cb502-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(</span>
<span id="cb502-2"><a href="date-time-data-with-lubridate.html#cb502-2" aria-hidden="true" tabindex="-1"></a>    Friends_visits <span class="sc">%&gt;%</span> </span>
<span id="cb502-3"><a href="date-time-data-with-lubridate.html#cb502-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Visit_hour_hms =</span> <span class="fu">hms</span>(Second, Minute, Hour))</span>
<span id="cb502-4"><a href="date-time-data-with-lubridate.html#cb502-4" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div>
<pre><code>## # A tibble: 6 x 10
##   Friend  Year Month   Day  Hour Minute Second Left_time          
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dttm&gt;             
## 1      1  2015     1     1    19      4     22 2015-01-01 08:30:00
## 2      2  2015     1     2     9     20     19 2015-01-02 08:50:00
## 3      4  2015     1     4     9     22     51 2015-01-04 10:04:00
## 4      5  2015     1     5    18      1     16 2015-01-05 08:12:00
## 5      6  2015     1     6     5     59      2 2015-01-06 07:40:00
## 6      7  2015     1     7     9     45     55 2015-01-07 09:13:00
## # ... with 2 more variables: Visit_time &lt;dttm&gt;, Visit_hour_hms &lt;time&gt;</code></pre>
<p>We can see that our “Visit_hour_hms” column actually only retain time (hour, minute, second) data directly. Using this column, we can plot our frequency polygon like so:</p>
<div class="sourceCode" id="cb504"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb504-1"><a href="date-time-data-with-lubridate.html#cb504-1" aria-hidden="true" tabindex="-1"></a> Friends_visits <span class="sc">%&gt;%</span> </span>
<span id="cb504-2"><a href="date-time-data-with-lubridate.html#cb504-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Visit_hour_hms =</span> <span class="fu">hms</span>(Second, Minute, Hour)) <span class="sc">%&gt;%</span></span>
<span id="cb504-3"><a href="date-time-data-with-lubridate.html#cb504-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(Visit_hour_hms)) <span class="sc">+</span></span>
<span id="cb504-4"><a href="date-time-data-with-lubridate.html#cb504-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_freqpoly</span>(<span class="at">binwidth =</span> <span class="dv">900</span>)</span></code></pre></div>
<p><img src="intro2R_files/figure-html/unnamed-chunk-274-1.png" width="672" /></p>
<p>If we compare this graph with the one above, we should see that they are identical! Except the x-axis in this graph is much clearer and accurate because it only contains the time of day.</p>
</div>
</div>
</div>
<div id="arithmetic-operators-with-datetime" class="section level2" number="7.8">
<h2><span class="header-section-number">7.8</span> Arithmetic Operators with Date/Time</h2>
<div id="basic-arithmetic" class="section level3" number="7.8.1">
<h3><span class="header-section-number">7.8.1</span> Basic Arithmetic</h3>
<p>Just like any other types of data on R, we can conduct basic arithmetic operations using date/time data.</p>
<div class="sourceCode" id="cb505"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb505-1"><a href="date-time-data-with-lubridate.html#cb505-1" aria-hidden="true" tabindex="-1"></a><span class="dv">5</span> <span class="sc">*</span> (<span class="fu">years</span>(<span class="dv">2</span>) <span class="sc">+</span> <span class="fu">months</span>(<span class="dv">11</span>))</span></code></pre></div>
<pre><code>## [1] &quot;10y 55m 0d 0H 0M 0S&quot;</code></pre>
<div class="sourceCode" id="cb507"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb507-1"><a href="date-time-data-with-lubridate.html#cb507-1" aria-hidden="true" tabindex="-1"></a><span class="fu">days</span>(<span class="dv">50</span>) <span class="sc">+</span> <span class="fu">hours</span>(<span class="dv">25</span>) <span class="sc">+</span> <span class="fu">minutes</span>(<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] &quot;50d 25H 2M 0S&quot;</code></pre>
<div class="sourceCode" id="cb509"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb509-1"><a href="date-time-data-with-lubridate.html#cb509-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ymd_hms</span>(<span class="st">&quot;2020-04-19 09:45:00&quot;</span>) <span class="sc">+</span></span>
<span id="cb509-2"><a href="date-time-data-with-lubridate.html#cb509-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">days</span>(<span class="dv">50</span>) <span class="sc">+</span> <span class="fu">hours</span>(<span class="dv">25</span>) <span class="sc">+</span> <span class="fu">minutes</span>(<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2020-06-09 10:47:00 UTC&quot;</code></pre>
<p>We can also combine arithmetic operators with <code>today()</code> or <code>now()</code> like the code below to find out someone’s age!</p>
<div class="sourceCode" id="cb511"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb511-1"><a href="date-time-data-with-lubridate.html#cb511-1" aria-hidden="true" tabindex="-1"></a>(age <span class="ot">&lt;-</span> <span class="fu">today</span>() <span class="sc">-</span> <span class="fu">ymd</span>(<span class="st">&quot;2000-02-15&quot;</span>))</span></code></pre></div>
<pre><code>## Time difference of 7873 days</code></pre>
<p>As you may have seen, telling someone you are 7,797 days old is quite a mouthful, and also pretty impractical. A way for us to make this number more comprehensible is by converting it to years using the function <code>as.duration()</code>.</p>
<div class="sourceCode" id="cb513"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb513-1"><a href="date-time-data-with-lubridate.html#cb513-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as.duration</span>(age)</span></code></pre></div>
<pre><code>## [1] &quot;680227200s (~21.56 years)&quot;</code></pre>
<div id="do-question-8-of-the-quiz-now-2" class="section level4 unnumbered">
<h4>DO QUESTION 8 OF THE QUIZ NOW</h4>
<ul>
<li>We can use <code>now()</code> to calculate our age as well. (True or False)</li>
</ul>
</div>
</div>
<div id="account-for-leap-years-and-daylight-savings" class="section level3" number="7.8.2">
<h3><span class="header-section-number">7.8.2</span> Account for Leap Years and Daylight Savings</h3>
<p>A potential problem with the functions that you are introduced to in the pr is that they do not account for time changes within the year. For example, a leap year can add an extra day to the year and daylight savings may add or subtract an hour from a day.</p>
<p>To solve this problem, we can use <code>dyears()</code> and <code>ddays()</code> instead of the normal <code>years()</code> and <code>days()</code>.</p>
<div id="leap-year" class="section level4" number="7.8.2.1">
<h4><span class="header-section-number">7.8.2.1</span> Leap Year</h4>
<p>We know that 2020 was a leap year. Let is check the difference between adding one year to 2020-01-01 using <code>years()</code> and <code>dyears()</code>.</p>
<div class="sourceCode" id="cb515"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb515-1"><a href="date-time-data-with-lubridate.html#cb515-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Normal</span></span>
<span id="cb515-2"><a href="date-time-data-with-lubridate.html#cb515-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb515-3"><a href="date-time-data-with-lubridate.html#cb515-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ymd</span>(<span class="st">&quot;2020-01-01&quot;</span>) <span class="sc">+</span> <span class="fu">years</span>(<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2021-01-01&quot;</code></pre>
<div class="sourceCode" id="cb517"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb517-1"><a href="date-time-data-with-lubridate.html#cb517-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Considers Leap Year</span></span>
<span id="cb517-2"><a href="date-time-data-with-lubridate.html#cb517-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb517-3"><a href="date-time-data-with-lubridate.html#cb517-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ymd</span>(<span class="st">&quot;2020-01-01&quot;</span>) <span class="sc">+</span> <span class="fu">dyears</span>(<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2020-12-31 06:00:00 UTC&quot;</code></pre>
<p>As we can see, <code>dyears()</code> accounts for an extra day in February, so it recognizes that 365 days (1 year) after 2020-01-01 is only 2020-12-31, not 2021-01-01.</p>
</div>
<div id="daylight-savings" class="section level4" number="7.8.2.2">
<h4><span class="header-section-number">7.8.2.2</span> Daylight Savings</h4>
<p>Similarly, <code>ddays()</code> recognizes that daylight savings in Vancouver started in early morning 2021-03-14, and correctly calculates that 1 day (24 hours) after 2021-03-14 1AM is actually 2021-03-15 2AM!</p>
<div class="sourceCode" id="cb519"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb519-1"><a href="date-time-data-with-lubridate.html#cb519-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Normal</span></span>
<span id="cb519-2"><a href="date-time-data-with-lubridate.html#cb519-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb519-3"><a href="date-time-data-with-lubridate.html#cb519-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ymd_hms</span>(<span class="st">&quot;2021-03-14 1:00:00&quot;</span>, </span>
<span id="cb519-4"><a href="date-time-data-with-lubridate.html#cb519-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">tz =</span> <span class="st">&quot;America/Vancouver&quot;</span>) <span class="sc">+</span> </span>
<span id="cb519-5"><a href="date-time-data-with-lubridate.html#cb519-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">days</span>(<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2021-03-15 01:00:00 PDT&quot;</code></pre>
<div class="sourceCode" id="cb521"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb521-1"><a href="date-time-data-with-lubridate.html#cb521-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Considers Daylight Savings</span></span>
<span id="cb521-2"><a href="date-time-data-with-lubridate.html#cb521-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb521-3"><a href="date-time-data-with-lubridate.html#cb521-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ymd_hms</span>(<span class="st">&quot;2021-03-14 1:00:00&quot;</span>, </span>
<span id="cb521-4"><a href="date-time-data-with-lubridate.html#cb521-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">tz =</span> <span class="st">&quot;America/Vancouver&quot;</span>) <span class="sc">+</span> </span>
<span id="cb521-5"><a href="date-time-data-with-lubridate.html#cb521-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ddays</span>(<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2021-03-15 02:00:00 PDT&quot;</code></pre>
</div>
<div id="do-questions-9-10-of-the-quiz-now" class="section level4 unnumbered">
<h4>DO QUESTIONS 9 &amp; 10 OF THE QUIZ NOW</h4>
<ul>
<li><p>Which of these functions account for date and time changes throughout the years?</p></li>
<li><p>What happens when we use <code>ddays()</code> or <code>dyears()</code> in days or years that do not experience any special time/date changes?</p></li>
</ul>
</div>
</div>
</div>
<div id="summary-and-takeaways-6" class="section level2" number="7.9">
<h2><span class="header-section-number">7.9</span> Summary and Takeaways</h2>
<p>After completing this tutorial, you should be more familiar the lubridate package and know the basic ways to deal with date/time data in R. This tutorial covered how to create new date/time data, retrieve information from existing date/time data, modify and plot date/time data, as well as conduct simple arithmetic operators using date/time data.</p>
<p>Date/time is quite interesting once you get the hang of it. This data type can give us very valuable information about the dataset that we are working with. Again, it is okay to make mistakes and be confused when we first got started, but know that fluency also comes from practice!</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-visualization-with-ggplot2.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="data-summary-with-tableone.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/ehsanx/intro2R/edit/master/6-date-time-data-with-lubridate.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["intro2R.pdf", "intro2R.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
